server:
  port: 8084

logging:
  pattern:
    console: "[RESOURCES-QUERY] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

# Actuator
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  data:
    mongodb:
      uri: mongodb://root:rootpassword@localhost:27017/?authSource=admin&authMechanism=SCRAM-SHA-1
      database: resources

axon:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: resources
      username: root
      password: rootpassword

spring.security.oauth2:
  resourceserver:
    jwt:
      issuer-uri: http://localhost:8081/auth/realms/jms
      jwk-set-uri: http://localhost:8081/auth/realms/jms/protocol/openid-connect/certs